/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY.
 * Generated by scripts/stamp-build.mjs, run from prebuild.
 *
 * Rotates which featured finding leads the homepage band. Advances by one on
 * every build, so a different finding leads after each deploy.
 */
export const BUILD_ROTATION = 5;
