/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY.
 * Generated by scripts/sync-publications.js
 * Source of truth: eigenia/references/
 * Total files indexed: 26
 */
import generatedData from "./generatedReferencesContent.json";

export interface DocMetadata {
  baseName: string;
  relativePath: string;
  wordCount: number;
  lineCount: number;
  charCount: number;
}

export const GENERATED_DOC_CONTENT: Record<string, string> = generatedData.content as Record<string, string>;

export const GENERATED_DOC_METADATA: Record<string, DocMetadata> = generatedData.metadata as Record<string, DocMetadata>;
