// Writes src/lib/buildStamp.ts, a single integer used to rotate which featured
// finding leads the homepage band.
//
// Why a generated constant rather than Math.random() in the component: the
// homepage is statically prerendered, and the band is a client component, so a
// value that differs between the server render and the client render is a
// hydration mismatch. Baking one number at build time means both sides agree,
// there is no layout shift, and crawlers see the same order a visitor does.
//
// The trade is that rotation happens per deploy rather than per visit. Across
// the thirteen findings, every one of them leads in turn.
//
// Deliberately tiny and free of imports. buildStamp.ts must never pull the
// generated content bundle; that is what would put 3.3 MB on the homepage.

import { writeFileSync, readFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";

const OUT = resolve(import.meta.dirname, "../src/lib/buildStamp.ts");

// Advance by one each build, wrapping well before any precision concern.
let previous = -1;
if (existsSync(OUT)) {
  const m = readFileSync(OUT, "utf8").match(/BUILD_ROTATION\s*=\s*(\d+)/);
  if (m) previous = Number(m[1]);
}
const next = (previous + 1) % 1000;

writeFileSync(
  OUT,
  `/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY.
 * Generated by scripts/stamp-build.mjs, run from prebuild.
 *
 * Rotates which featured finding leads the homepage band. Advances by one on
 * every build, so a different finding leads after each deploy.
 */
export const BUILD_ROTATION = ${next};
`,
  "utf8"
);

console.log(
  `[stamp-build] BUILD_ROTATION ${previous === -1 ? "initialised to" : previous + " ->"} ${next}`
);
